### ISSUE TITLE
find() will return 0 if the prediction is the choice label itself, without any extra string (e.g. answer:) 

### ISSUE THREAD

**Issue by Mooler0410** [open-compass/Ada-LEval#2]
https://github.com/open-compass/Ada-LEval/blob/a29c69e3ca2b0a59eaf9ae4114453e938c08d57c/ada_leval/dataset.py#L85

This line should be changed to '> -1 * nc'.

For example: 

prediction : 'A11'
ground truth: 'A11'

In this case, find() will return 0, and it does not meet the condition: >=1. 
However, it's still a correct answer. 

find() return -1 rather than 0, if it truly cannot match something.

**Comment by kennymckormick** [comment]
Hi, @Mooler0410,
Thanks a lot, it seems to be some typos in our released minimal example, we will create a PR to fix it ASAP.

**Comment by kennymckormick** [comment]
Fixed in #3

**Comment by Mooler0410** [comment]
Thank you for your quick and supportive response!
