### ISSUE TITLE
Will this benchmark be added to the opencompass evaluation framework?

### ISSUE THREAD

**Issue by young-chao** [open-compass/Ada-LEval#4]
I have tried many benchmarks, including implementing my own, and I think BestAnswer Evaluation is the most reliable recently for evaluating long context capability of LLM, especially in terms of code-related capabilities.
At present, I have rewritten the inference and evaluation code based on the current implementation to support the evaluation of more models directly based on VLLM as a temporary solution. 
I would like to know if this benchmark will be added to OPENCOMPASS in the near future. I think this will be more convenient for scientific research.

**Comment by philipwangOvO** [comment]
Thank you for the attention and recognition of our benchmarks. However, we have decided not to add them to OpenCompass in the near future. We still appreciate the integration of this dataset to OpenCompass.

**Comment by young-chao** [comment]
Thank you for your reply.
